<img src="https://www.uc3m.es/ss/Satellite?blobcol=urldata&blobkey=id&blobtable=MungoBlobs&blobwhere=1371573952659">


---


# **WEB ANALYTICS COURSE 4 - SEMESTER 2**
# **BACHELOR IN DATA SCIENCE AND ENGINEERING**

# **LAB 1 APIs - WORLD BANK**

## *Participants:*

Beltrán Valero 100451816

Annunziata Álvarez-Cascos 100451939

Gracia Estrán 100452014

Marta Almagro 100451979

# 0. LAB PREPARATION

Students have to complete the following tasks before attedning the lab:

1. **Read and study the API documentation to have some initial notions of the functionality of the World Bank API. Following, we share several links to the documentation related to the World Bank API:**
- https://datahelpdesk.worldbank.org/knowledgebase/articles/898581-api-basic-call-structures
- https://datahelpdesk.worldbank.org/knowledgebase/topics/125589-developer-information
- https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation

2. **The key element of the World Bank API are the "indicators". Next, we share a link that may simplify the search of indicators through a search tool. Once you have selected an indicator you can find its codification within the url bar of the browser.**

- https://data.worldbank.org/indicator?tab=featured
- https://data.worldbank.org/indicator/IQ.CPA.PUBS.XQ?view=chart
- https://data.worldbank.org/indicator/AG.LND.IRIG.AG.ZS?view=chart

# **1. INTRODUCTION**

* The goal of this lab is to gain experience testing a widely-used API such as the World Bank API that includes bunch of information about countries indicators in economy, health, education, agriculture, etc.

* The lab includes 5 milestones that will drive the student through the use of several indicators.  

* The lab will be done in groups of 23 students.

* The lab will use two complete consecutive sessions (4 hours). The students are expected to complete the 5 milestones proposed in the lab within these 2 sessions

* **The final mark will be computed as a function of the number of milestones successfully completed.**

* **Each group should also upload their lab notebook in the corresponding task in Aula Global.**

* Upon completing all the milestones, students should call the professor, who will check the correctness of the solution. Partial milestones checks may be allowed in some cases.

# 2. **MILESTONES**

In this section we describe one by one the milestones and leave a space to the students to implement the code to complete the requested task.

**NOTE: Unless otherwise stated, all the milestones have to deliver information about countries. Therefore, you should not consider regions or any othre aggreated information in your analysis.**

# **2.1. MILESTONE 1: POPULATION**:
Retrieve the 2022 countries' population and show the Top 10 countries and the Bottom 10 countries within the World Bank database.

In [ ]:
# Import the necessary libraries
import requests
import pandas as pd

After trying different links we found out which part is the codification indicator of the countries' population.

Also we used "api.worldbank.org" in the base URL for the World Bank's API. This way we will be able to make requests for a structured format JSON (and avoid the error: JSONDecodeError: Expecting value: line 1 column 1 (char 0))

In [ ]:
indicator = 'SP.POP.TOTL'
url = 'https://api.worldbank.org/v2/country/indicator/' + indicator + '?format=json&date=2022&per_page=20000'

Retrieve the data and convert it into a pandas dataframe so we have an easy access to it:

In [ ]:
response = requests.get(url)
data = response.json() # dictionary or a list of dictionaries
df = pd.DataFrame(data[1])
df

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,720839314.0,,,0
1,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'ZI', 'value': 'Africa Western and Cent...",AFW,2022,490330870.0,,,0
2,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': '1A', 'value': 'Arab World'}",ARB,2022,464684914.0,,,0
3,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'S3', 'value': 'Caribbean small states'}",CSS,2022,7505478.0,,,0
4,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'B8', 'value': 'Central Europe and the ...",CEB,2022,100648571.0,,,0
...,...,...,...,...,...,...,...,...
261,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'VI', 'value': 'Virgin Islands (U.S.)'}",VIR,2022,105413.0,,,0
262,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'PS', 'value': 'West Bank and Gaza'}",PSE,2022,5043612.0,,,0
263,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'YE', 'value': 'Yemen, Rep.'}",YEM,2022,33696614.0,,,0
264,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'ZM', 'value': 'Zambia'}",ZMB,2022,20017675.0,,,0
265,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,2022,16320537.0,,,0

We added a new column with just the name of the countries so the printed results are clear and without any irrelevant data:

In [ ]:
# Get the country name out of the dictionary and create a new column
df['country_name'] = [country['value'] for country in df['country']]
df

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal,country_name
0,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,720839314.0,,,0,Africa Eastern and Southern
1,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'ZI', 'value': 'Africa Western and Cent...",AFW,2022,490330870.0,,,0,Africa Western and Central
2,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': '1A', 'value': 'Arab World'}",ARB,2022,464684914.0,,,0,Arab World
3,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'S3', 'value': 'Caribbean small states'}",CSS,2022,7505478.0,,,0,Caribbean small states
4,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'B8', 'value': 'Central Europe and the ...",CEB,2022,100648571.0,,,0,Central Europe and the Baltics
...,...,...,...,...,...,...,...,...,...
261,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'VI', 'value': 'Virgin Islands (U.S.)'}",VIR,2022,105413.0,,,0,Virgin Islands (U.S.)
262,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'PS', 'value': 'West Bank and Gaza'}",PSE,2022,5043612.0,,,0,West Bank and Gaza
263,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'YE', 'value': 'Yemen, Rep.'}",YEM,2022,33696614.0,,,0,"Yemen, Rep."
264,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'ZM', 'value': 'Zambia'}",ZMB,2022,20017675.0,,,0,Zambia
265,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,2022,16320537.0,,,0,Zimbabwe

At this point, we noticed that we were not getting the desired results by country but by aggregations or zones, so we decided to get the tag for each country.

In [ ]:
#query without indicator to get all countries
url = 'https://api.worldbank.org/v2/country/?format=json&date=2022&per_page=20000'

In [ ]:
response = requests.get(url)
data = response.json() # dictionary or a list of dictionaries
df_countries = pd.DataFrame(data[1])
df_countries

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
2,AFG,AF,Afghanistan,"{'id': 'SAS', 'iso2code': '8S', 'value': 'Sout...","{'id': 'SAS', 'iso2code': '8S', 'value': 'Sout...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228
3,AFR,A9,Africa,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
4,AFW,ZI,Africa Western and Central,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
...,...,...,...,...,...,...,...,...,...,...
292,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
293,YEM,YE,"Yemen, Rep.","{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Sana'a,44.2075,15.352
294,ZAF,ZA,South Africa,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Pretoria,28.1871,-25.746
295,ZMB,ZM,Zambia,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Lusaka,28.2937,-15.3982
296,ZWE,ZW,Zimbabwe,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'}",Harare,31.0672,-17.8312

We noticed that in the *region* column the rows that are not countries but groups of countries, the value is *Aggregates*. So we removed those rows from our dataset to keep only countries.

In [ ]:
df_countries['region_name'] = [id['value'] for id in df_countries['region']] #this creates a column with the region value
#df_countries
f_df_countries = df_countries[df_countries['region_name'] != 'Aggregates'] #this filters our dataset only for countries and not aggregations
f_df_countries

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude,region_name
0,ABW,AW,Aruba,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167,Latin America & Caribbean
2,AFG,AF,Afghanistan,"{'id': 'SAS', 'iso2code': '8S', 'value': 'Sout...","{'id': 'SAS', 'iso2code': '8S', 'value': 'Sout...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228,South Asia
5,AGO,AO,Angola,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Luanda,13.242,-8.81155,Sub-Saharan Africa
6,ALB,AL,Albania,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro...","{'id': 'ECA', 'iso2code': '7E', 'value': 'Euro...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Tirane,19.8172,41.3317,Europe & Central Asia
7,AND,AD,Andorra,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Andorra la Vella,1.5218,42.5075,Europe & Central Asia
...,...,...,...,...,...,...,...,...,...,...,...
291,XKX,XK,Kosovo,"{'id': 'ECS', 'iso2code': 'Z7', 'value': 'Euro...","{'id': 'ECA', 'iso2code': '7E', 'value': 'Euro...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Pristina,20.926,42.565,Europe & Central Asia
293,YEM,YE,"Yemen, Rep.","{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Sana'a,44.2075,15.352,Middle East & North Africa
294,ZAF,ZA,South Africa,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Pretoria,28.1871,-25.746,Sub-Saharan Africa
295,ZMB,ZM,Zambia,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Lusaka,28.2937,-15.3982,Sub-Saharan Africa
296,ZWE,ZW,Zimbabwe,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'}",Harare,31.0672,-17.8312,Sub-Saharan Africa

Now we are going to store all the countries' labels or codes (which are in the *iso2Code* column) in a list, so that we can filter the first dataset we had (df) with the population information we want.

In [ ]:
codes = [] #list to store the countries' codes
for code in f_df_countries['iso2Code']:
  codes.append(code)

# codes

In [ ]:
df['country_code'] = [country['id'] for country in df['country']] #first we add a column with the codes
#df
final_df = df[df['country_code'].isin(codes)] #filter by the codes corresponding to countries
final_df

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal,country_name,country_code
49,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'AF', 'value': 'Afghanistan'}",AFG,2022,41128771.0,,,0,Afghanistan,AF
50,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'AL', 'value': 'Albania'}",ALB,2022,2775634.0,,,0,Albania,AL
51,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'DZ', 'value': 'Algeria'}",DZA,2022,44903225.0,,,0,Algeria,DZ
52,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2022,44273.0,,,0,American Samoa,AS
53,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'AD', 'value': 'Andorra'}",AND,2022,79824.0,,,0,Andorra,AD
...,...,...,...,...,...,...,...,...,...,...
261,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'VI', 'value': 'Virgin Islands (U.S.)'}",VIR,2022,105413.0,,,0,Virgin Islands (U.S.),VI
262,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'PS', 'value': 'West Bank and Gaza'}",PSE,2022,5043612.0,,,0,West Bank and Gaza,PS
263,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'YE', 'value': 'Yemen, Rep.'}",YEM,2022,33696614.0,,,0,"Yemen, Rep.",YE
264,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'ZM', 'value': 'Zambia'}",ZMB,2022,20017675.0,,,0,Zambia,ZM
265,"{'id': 'SP.POP.TOTL', 'value': 'Population, to...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,2022,16320537.0,,,0,Zimbabwe,ZW

Finally, we sorted and retrieved the top (bottom) ten results to show them in order:

In [ ]:
# Top 10 countries
top_10 = final_df.sort_values(by='value', ascending=False).head(10)

# Print the results (Top 10)
print("Top 10 Countries by Population in 2022:")
print(top_10[['country_name', 'value']])

Top 10 Countries by Population in 2022:
           country_name         value
138               India  1.417173e+09
90                China  1.412175e+09
255       United States  3.332876e+08
139           Indonesia  2.755013e+08
198            Pakistan  2.358249e+08
193             Nigeria  2.185412e+08
75               Brazil  2.153135e+08
64           Bangladesh  1.711864e+08
210  Russian Federation  1.435557e+08
176              Mexico  1.275041e+08

In [ ]:
# Bottom 10 countries
bottom_10 = final_df.sort_values(by='value').head(10)

# Print the results (Bottom 10)
print("Bottom 10 Countries by Population in 2022:")
print(bottom_10[['country_name', 'value']])

Bottom 10 Countries by Population in 2022:
                 country_name    value
250                    Tuvalu  11312.0
186                     Nauru  12668.0
199                     Palau  18055.0
76     British Virgin Islands  31305.0
232  St. Martin (French part)  31791.0
124                 Gibraltar  32649.0
213                San Marino  33660.0
179                    Monaco  36469.0
163             Liechtenstein  39327.0
173          Marshall Islands  41569.0

# **2.2. MILESTONE 2: WOMEN Vs. MEN POPULATION**:
Obtain the % of men and women for each country and compute the difference among them using the formula %women - %men. Display:

1- The number of countries with more women than men.

2- The number of countries with more men than women

3- The 10 countries with more women compared to men (ten countries with the largest positive value of the previous metric)

- The 10 countries with more men compared to women (ten countries with the largest negative value of the previous metric).

**Note**: You can use the indicator the absolute number of men and women from the World Bank API and compute the % for each country and the difference, or you can use the indicator given directly the %.

#### Data request and structuring into data frame

To begin with, we got 2 separate datasets with the data corresponding to the Percentage of population of women and of men for each country. Later we found out both codification indicators for the percentage of total population of women and men, and we stored the results of the get in a json.

In [ ]:
indicator_women = 'SP.POP.TOTL.FE.ZS' #Population, female (% of total population)
indicator_men = 'SP.POP.TOTL.MA.ZS' #Population, male (% of total population)
url_women = 'https://api.worldbank.org/v2/country/indicator/' + indicator_women + '?format=json&per_page=20000&date=2022'
url_men = 'https://api.worldbank.org/v2/country/indicator/' + indicator_men + '?format=json&per_page=20000&date=2022'

# Send the GET requests to the World Bank API
response_women = requests.get(url_women)
response_men = requests.get(url_men)

#both are dictionary or a list of dictionaries
wdata = response_women.json()
mdata = response_men.json()

#convert the json to dataset
wdf = pd.DataFrame(wdata[1])
mdf = pd.DataFrame(mdata[1])
wdf

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,50.472433,,,1
1,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'ZI', 'value': 'Africa Western and Cent...",AFW,2022,49.725969,,,1
2,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': '1A', 'value': 'Arab World'}",ARB,2022,48.326771,,,1
3,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'S3', 'value': 'Caribbean small states'}",CSS,2022,50.645728,,,1
4,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'B8', 'value': 'Central Europe and the ...",CEB,2022,51.556766,,,1
...,...,...,...,...,...,...,...,...
261,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'VI', 'value': 'Virgin Islands (U.S.)'}",VIR,2022,53.385613,,,1
262,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'PS', 'value': 'West Bank and Gaza'}",PSE,2022,50.106341,,,1
263,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'YE', 'value': 'Yemen, Rep.'}",YEM,2022,49.480969,,,1
264,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'ZM', 'value': 'Zambia'}",ZMB,2022,50.655398,,,1
265,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,2022,52.785855,,,1

#### Filtering our data

Again we have to filter by the code to get only the countries and not groups, so we will use again the auxiliary list we created with the countries' codes.

In [ ]:
wdf['country_code'] = [country['id'] for country in wdf['country']] #first we add a column with the codes
mdf['country_code'] = [country['id'] for country in wdf['country']] #first we add a column with the codes
#wdf
wdf = wdf[wdf['country_code'].isin(codes)] #filter by the codes corresponding to countries
mdf = mdf[mdf['country_code'].isin(codes)] #filter by the codes corresponding to countries
wdf

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal,country_code
49,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'AF', 'value': 'Afghanistan'}",AFG,2022,49.508722,,,1,AF
50,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'AL', 'value': 'Albania'}",ALB,2022,50.117738,,,1,AL
51,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'DZ', 'value': 'Algeria'}",DZA,2022,49.085532,,,1,DZ
52,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'AS', 'value': 'American Samoa'}",ASM,2022,50.592912,,,1,AS
53,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'AD', 'value': 'Andorra'}",AND,2022,48.905091,,,1,AD
...,...,...,...,...,...,...,...,...,...
261,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'VI', 'value': 'Virgin Islands (U.S.)'}",VIR,2022,53.385613,,,1,VI
262,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'PS', 'value': 'West Bank and Gaza'}",PSE,2022,50.106341,,,1,PS
263,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'YE', 'value': 'Yemen, Rep.'}",YEM,2022,49.480969,,,1,YE
264,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'ZM', 'value': 'Zambia'}",ZMB,2022,50.655398,,,1,ZM
265,"{'id': 'SP.POP.TOTL.FE.ZS', 'value': 'Populati...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,2022,52.785855,,,1,ZW

#### Structuring and transforming our data

Then, we added a column with the name of each country to both datasets. Afterwards, we merged both datasets by mapping the country name and keeping the value for the % of men and the % of women. Then, we added a column with the difference between the percentage of women and the percentage of men.

In [ ]:
# Get the country name out of the dictionary and create a new column
wdf['country_name'] = [country['value'] for country in wdf['country']]
mdf['country_name'] = [country['value'] for country in mdf['country']]

wdf = wdf.rename(columns={'value': 'value_women'})
mdf = mdf.rename(columns={'value': 'value_men'})

#Merge both dataframes so that we can compute the operations with the values of both
df = pd.merge(wdf[['country_name', 'value_women','date']], mdf[['country_name', 'value_men','date']], on=['country_name','date'], how='inner')

#Create a new column with the diference: %women - %men
df['difference'] = df['value_women'] - df['value_men']

df  #preview of our data

<ipython-input-72-1cdf38b20bb4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wdf['country_name'] = [country['value'] for country in wdf['country']]

              country_name  value_women  date  value_men  difference
0              Afghanistan    49.508722  2022  50.491278   -0.982555
1                  Albania    50.117738  2022  49.882227    0.235512
2                  Algeria    49.085532  2022  50.914465   -1.828933
3           American Samoa    50.592912  2022  49.404829    1.188083
4                  Andorra    48.905091  2022  51.094909   -2.189818
..                     ...          ...   ...        ...         ...
212  Virgin Islands (U.S.)    53.385613  2022  46.613382    6.772231
213     West Bank and Gaza    50.106341  2022  49.893678    0.212664
214            Yemen, Rep.    49.480969  2022  50.519031   -1.038063
215                 Zambia    50.655398  2022  49.344602    1.310797
216               Zimbabwe    52.785855  2022  47.214139    5.571716

[217 rows x 5 columns]

#### Calculalting the desired results

Now that we have the data needed in our dataset we can calculate the number of countries with more women than men, more men than women and the top 10 countries of each one. This was easy thanks to the column we created with the difference in the percentages (i.e., the positive values of "difference" belong to the countries with more women than men, and the positive values to the countries with more men than women)

In [ ]:
#1- The number of countries with more women than men. (Difference column is possitive)
more_women = df[df['difference']>0]
print("The number of countries with more women than men is:", len(more_women))
#print(more_women)

#2- The number of countries with more men than women
more_men = df[df['difference']<0]
print("The number of countries with more men than women is:", len(more_men))

#3A- The 10 countries with more women compared to men (ten countries with the largest positive value of the previous metric)
top_10_women = more_women.sort_values(by='difference', ascending=False).head(10)

print("Top 10 countries with more women compared to men:")
print(top_10_women[['country_name', 'value_women','difference']])

#3B- The 10 countries with more men compared to women (ten countries with the largest negative value of the previous metric).
top_10_men = more_men.sort_values(by='difference', ascending=True).head(10)

print("Top 10 countries with more men compared to women:")
print(top_10_men[['country_name', 'value_men','difference']])

The number of countries with more women than men is: 136
The number of countries with more men than women is: 81
Top 10 countries with more women compared to men:
              country_name  value_women  difference
8                  Armenia    55.040714   10.081429
203                Ukraine    54.080923    8.161847
17                 Belarus    53.956097    7.912183
86    Hong Kong SAR, China    53.926676    7.853353
109                 Latvia    53.615241    7.230537
161     Russian Federation    53.557528    7.115055
212  Virgin Islands (U.S.)    53.385613    6.772231
117       Macao SAR, China    53.078968    6.157936
115              Lithuania    53.031521    6.063042
72                 Georgia    52.996286    5.992546
Top 10 countries with more men compared to women:
                  country_name  value_men  difference
159                      Qatar  72.510001  -45.020003
204       United Arab Emirates  69.353400  -38.706801
14                     Bahrain  61.960233  -23.920466
148                       Oman  60.867846  -21.735691
106                     Kuwait  60.811085  -21.622147
166               Saudi Arabia  57.621293  -15.242590
121                   Maldives  57.526246  -15.052684
146   Northern Mariana Islands  53.752699   -7.505398
172  Sint Maarten (Dutch part)  53.534805   -7.069610
22                      Bhutan  52.901445   -5.802890

## **2.3. MILESTONE 3: GDP PER CAPITA ACCORDING FOR INCOME LEVEL GROUPS**:

Compute the average increase/decrease in percentage for the PIB per capita in US dollars in the following two periods: 2000-2022 and  2010-2022, for the following income groups: low-income economies, lower-middle-income economies, middle economies, upper-middle-income economies and high-income economies. The following, link provides information of the different country aggregations carried out by the World Bank.  

https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups

 You should compute the %PIB increase as follows. Given country A with a PIB Per Capita \$20000 in 2000 and \$30000 in 2022 the increase/decrease should be computed as follow:

%PIB increase = 100*(30000-20000)/20000=50%.

#### Data request and structuring into data frame

We began by getting the dataset with the data corresponding to the PIB per capita (GDP) in US dollars, by finding out the codification indicator for it and storing the results of the get in a json.

In [ ]:
indicator = 'NY.GDP.PCAP.CD' #indicator code for GDP per capita (current US$)
url = 'https://api.worldbank.org/v2/country/all/indicator/' + indicator + '?format=json&per_page=20000'

response = requests.get(url) # Send the GET request to the World Bank API
data = response.json() # dictionary or a list of dictionaries (json format)
df = pd.DataFrame(data[1]) #convert to dataset
df #preview of the raw dataset

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'NY.GDP.PCAP.CD', 'value': 'GDP per cap...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,1622.391720,,,1
1,"{'id': 'NY.GDP.PCAP.CD', 'value': 'GDP per cap...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,1539.165543,,,1
2,"{'id': 'NY.GDP.PCAP.CD', 'value': 'GDP per cap...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2020,1353.927527,,,1
3,"{'id': 'NY.GDP.PCAP.CD', 'value': 'GDP per cap...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2019,1499.954437,,,1
4,"{'id': 'NY.GDP.PCAP.CD', 'value': 'GDP per cap...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2018,1550.111762,,,1
...,...,...,...,...,...,...,...,...
16753,"{'id': 'NY.GDP.PCAP.CD', 'value': 'GDP per cap...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1964,282.376856,,,1
16754,"{'id': 'NY.GDP.PCAP.CD', 'value': 'GDP per cap...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1963,277.532515,,,1
16755,"{'id': 'NY.GDP.PCAP.CD', 'value': 'GDP per cap...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1962,275.966139,,,1
16756,"{'id': 'NY.GDP.PCAP.CD', 'value': 'GDP per cap...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1961,279.332656,,,1
16757,"{'id': 'NY.GDP.PCAP.CD', 'value': 'GDP per cap...","{'id': 'ZW', 'value': 'Zimbabwe'}",ZWE,1960,276.643363,,,1

#### Year range filtering step and calculation of % of PIB increase

Now we will perform some data cleaning and filtering in the raw dataset to get a structured df with the information we want. We add a column with the name of each country and filter the date columns to keep only the years we are interested in (2000, 2010 and 2022). With this information we can calculate the % of PIB increase as indicated above. Lastly, we will delete values with na values, as they will not give any result for the % of increase.

In [ ]:
# Get the country name out of the dictionary and create a new column
df['country_name'] = [country['value'] for country in df['country']] #add column for the country name


df = df.pivot(index = 'country_name', columns = 'date', values = 'value')[['2000', '2010', '2022']] #keep only data for the years of interest

# Create columns with the percentage of increase in the PIB for the 2 desired ranges of years
df['% of PIB increase 2000 to 2022'] = 100*(df['2022']- df['2000'])/df['2000']
df['% of PIB increase 2010 to 2022'] = 100*(df['2022']- df['2010'])/df['2010']

df_years = df.dropna() #data cleaning

df_years

date,2000,2010,2022,% of PIB increase 2000 to 2022,% of PIB increase 2010 to 2022
country_name,,,,,
Africa Eastern and Southern,709.061010,1649.639146,1622.391720,128.808480,-1.651720
Africa Western and Central,522.772772,1679.646727,1790.348800,242.471700,6.590795
Albania,1126.683340,4094.349699,6802.804519,503.790282,66.151038
Algeria,1780.376071,4495.921455,4273.922183,140.057270,-4.937792
Andorra,21620.468488,48237.891173,41992.793358,94.227028,-12.946457
...,...,...,...,...,...
Vietnam,394.583137,1684.011667,4163.514300,955.167825,147.237854
West Bank and Gaza,1476.171850,2557.075624,3789.327966,156.699650,48.189906
World,5508.433014,9558.021731,12647.480789,129.602153,32.323206
Zambia,364.026126,1469.361450,1487.907764,308.736533,1.262202
Zimbabwe,565.284390,937.840340,1266.996031,124.134268,35.097199

#### Income groups filtering step

In the previous step we noticed that the country column in our first dataframe already contained the information we wanted about the PIB income by income groups, so it was simpler for us. So we only had to keep those groups in order to have the desired results.

In [ ]:
groups = ['Low income','Lower middle income','Middle income','Upper middle income','High income'] #list with names of each income group as they appear in the dataframe above

groups_df = df_years[df_years.index.isin(groups)] #keep only the desired columns (the ones in the groups list)
groups_df = groups_df.rename_axis('Income groups') #change name of index
groups_df

date,2000,2010,2022,% of PIB increase 2000 to 2022,% of PIB increase 2010 to 2022
Income groups,,,,,
High income,25191.046014,38764.446900,49430.329365,96.221822,27.514600
Low income,487.481211,1158.035751,741.244363,52.055986,-35.991237
Lower middle income,601.113227,1690.256779,2542.199938,322.915321,50.403180
Middle income,1246.291443,3788.503993,6388.158169,412.573380,68.619544
Upper middle income,1860.112875,5979.911295,10794.931857,480.337463,80.519933

# **2.4. MILESTONE 4: TOP 5 COUNTRIES INCREASE GDP PER INCOME-GROUP**

For each of the income groups included in Milestone 3 and the period 2010-2022 list the Top 5 countries in terms of %GDPR per capita increase along with the value

**NOTE**: Do not consider the countries for which you do not have data either in 2010 or 2022 or both of them

In [ ]:
import requests
import pandas as pd

# Income levels: 'High income'--> 'HIC'/ 'Low income'--> 'LIC'/ 'Lower middle income'--> 'LMC'/ 'Middle income'--> No entries/ 'Upper middle income'-->'UMC'
incomeLevels = ['HIC', 'LIC', 'LMC', 'UMC']
countries = {}

for i in incomeLevels:
  url = f'http://api.worldbank.org/V2/country?incomeLevel={i}&format=json&per_page=1000'
  response = requests.get(url)
  data = response.json()[1]

  df = pd.DataFrame(data)
  countries[i] = list(df['id'])

  countryNames = []
  gdp2010 = []
  gdp2022 = []

  for id in countries[i]:
    url2010 = f'https://api.worldbank.org/v2/country/{id}/indicators/' + indicator + '?format=json&date=2010&per_page=4000'
    url2022 = f'https://api.worldbank.org/v2/country/{id}/indicators/' + indicator + '?format=json&date=2022&per_page=4000'

    response2010 = requests.get(url2010)
    data2010 = response2010.json()[1]

    response2022 = requests.get(url2022)
    data2022 = response2022.json()[1]
    if data2010 is not None:
      countryNames.append(data2010[0]['country']['value'])
      gdp2010.append(data2010[0]['value'])
      gdp2022.append(data2022[0]['value'])

  income = pd.DataFrame({'Country': countryNames, 'GDP2010': gdp2010, 'GDP2022': gdp2022})

  gdpIncrease = []

  for idx, row in income.iterrows():
    gdpIncrease.append(100*(row[2]-row[1]/row[1]))

  income['Increase-GDP'] = gdpIncrease

  top5_group = income.nlargest(5, 'Increase-GDP')
  print(i,'level:')
  print(top5_group)

HIC level:
        Country        GDP2010        GDP2022  Increase-GDP
48   Luxembourg  110885.991379  126426.089934  1.264251e+07
10      Bermuda  101875.284073  118845.621104  1.188446e+07
57       Norway   88163.208593  106148.778628  1.061478e+07
38      Ireland   48663.600444  104038.946076  1.040379e+07
14  Switzerland   76531.372941   92101.469741  9.210047e+06
LIC level:
     Country      GDP2010      GDP2022   Increase-GDP
17     Sudan  1706.414917  1102.146484  110114.648438
6   Ethiopia   335.438495  1027.585918  102658.591828
16    Rwanda   594.109512   966.327110   96532.711011
24    Uganda   824.737671   964.224385   96322.438522
23      Togo   709.140670   918.376756   91737.675579
LMC level:
               Country      GDP2010      GDP2022   Increase-GDP
31            Mongolia  2660.288176  4946.754811  494575.481126
47             Ukraine  3078.414795  4533.975586  453297.558594
19  Iran, Islamic Rep.  6458.573956  4387.825715  438682.571518
12    Egypt, Arab Rep.  2509.772034  4295.407496  429440.749561
11             Algeria  4495.921455  4273.922183  427292.218312
UMC level:
               Country       GDP2010       GDP2022  Increase-GDP
42  Russian Federation  10674.990234  15345.096680  1.534410e+06
4             Bulgaria   6862.757687  13772.476794  1.377148e+06
1            Argentina  10385.964432  13686.008674  1.368501e+06
12          Costa Rica   8147.243985  13198.821717  1.319782e+06
10               China   4550.473924  12720.215640  1.271922e+06

# **2.5. MILESTONE 5: CO2 emission per capita**

Retrieve the most recent non empty value for the amount of CO2 emission per capita (metric tons per country) for all the countries. Display the 30 countries with the highest CO2 emission per capita along with their value and the year related to that value.

**NOTE**: You cannot search manually the year and use it in your query for this milestone.

#### Data request and structuring into data frame
We did the same process than in the previous milestones to get the data we wanted, including the step of adding a column with the country name and delete the empty data.

In [ ]:
indicator = 'EN.ATM.CO2E.PC' #CO2 emissions (metric tons per capita)
url = 'https://api.worldbank.org/v2/country/indicator/' + indicator + '?format=json&per_page=20000'
response = requests.get(url)
data = response.json() # dictionary or a list of dictionaries
df = pd.DataFrame(data[1])
df['country_name'] = [country['value'] for country in df['country']] #add column with the country name
df = df.dropna() #delete empty data

df #preview of our data

In [ ]:
df['country_code'] = [country['id'] for country in df['country']] #first we add a column with the codes
df = df[df['country_code'].isin(codes)] #filter by the codes corresponding to countries
df

#### Select the most recent value for each country in a non-manual way

To keep the most recent row (latest date) for each country in our dataset, we first sorted our data by the 'date' column in descending order and then we eliminated the duplicates by 'country_name', so that we could keep only the most recent value for each country.

In [ ]:
# Sort the dataset by the 'date' to get the most recent year
df.sort_values(by='date', ascending=False, inplace=True)

#Eliminate duplicate values keeping only the first row of each country ( so it is the most recent value)
df = df.drop_duplicates(subset='country_name', keep='first')

df #preview of our data

Then we got the top 30 countries by the value of CO2 emission by sorting our data by the column value:

In [ ]:
#Top 30
top_30 = df.sort_values(by='value', ascending=False).head(30)

# Print the results (Top 30)
print("Top 30 countries with the highest CO2 emission per capita:")
print(top_30[['country_name','value','date']])